source 'http://rubygems.org'

gem 'puppet', '~> 3.8'
gem 'rake'
gem 'tilt'
gem 'librarian-puppet'
gem 'test-kitchen'

gem 'win32-dir'
gem 'win32-process'
gem 'win32-service'
gem 'ffi'

gem 'metadata-json-lint'
gem 'puppetlabs_spec_helper'
gem 'puppet-lint'

gem 'vagrant-wrapper'
gem 'kitchen-vagrant'
gem 'kitchen-ssh'
gem 'kitchen-puppet'
gem 'kitchen-sync'
gem 'kitchen-verifier-serverspec'
gem 'net-ssh'
gem 'serverspec'
gem 'rspec_junit_formatter'
